# Generated by Django 3.2.12 on 2022-03-20 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220318_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2022, message='Год не может быть больше текущего!')]),
        ),
    ]
