# Generated by Django 3.2.12 on 2022-03-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_alter_category_slug'),
        ('reviews', '0016_alter_review_title'),
    ]

    operations = [
    ]
